language: java
jdk:
  - oraclejdk8

before_install:
  - echo "task wrapper (type" ":Wrapper) {gradleVersion='3.4'}" > nada.gradle
  - cat nada.gradle
  - gradle -b nada.gradle wrapper
  - ./gradlew --version
  
script:
  - ./gradlew --version
  - ./gradlew tasks
  